import type { LangText } from "@/i18n/types";
const L = (es: string, en: string, de: string, pt: string): LangText => ({es,en,de,pt});
export const RX = {
  title: L("Radiografía de tu tienda Shopify | Monza Lab", "Your Shopify store review | Monza Lab", "Dein Shopify-Store im Check | Monza Lab", "Radiografia da tua loja Shopify | Monza Lab"),
  eyebrow: L("Para tiendas Shopify que ya venden", "For Shopify stores already selling", "Für Shopify-Stores, die bereits verkaufen", "Para lojas Shopify que já vendem"),
  heading: L("Recibes visitas.", "You get visitors.", "Du hast Besucher.", "Recebes visitas."),
  accent: L("¿Qué frena la compra?", "What holds back the sale?", "Was bremst den Kauf?", "O que trava a compra?"),
  sub: L("Revisamos tu tienda y te mostramos cómo replantear una ficha de producto, con una versión funcional al lado de la actual.", "We review your store and show you how we'd rethink a product page, with a working version beside your current one.", "Wir prüfen deinen Store und zeigen, wie wir eine Produktseite neu aufbauen würden: eine funktionierende Version neben deiner aktuellen Seite.", "Analisamos a tua loja e mostramos como repensar uma página de produto, com uma versão funcional ao lado da atual."),
  cta: L("Pedir mi radiografía", "Request my review", "Meine Analyse anfordern", "Pedir a minha radiografia"),
  terms: L("Gratis · 3 marcas al mes · 72 horas con cupo confirmado", "Free · 3 brands a month · 72 hours once your slot is confirmed", "Kostenlos · 3 Marken im Monat · 72 Stunden nach Terminbestätigung", "Grátis · 3 marcas por mês · 72 horas após confirmação da vaga"),
  formTitle: L("Empecemos por tu tienda.", "Let's start with your store.", "Beginnen wir mit deinem Store.", "Comecemos pela tua loja."),
  formSub: L("Deja tu link y tus datos. Edgar te confirma el cupo y la fecha de entrega.", "Leave your link and contact details. Edgar will confirm your slot and delivery date.", "Hinterlasse deinen Link und deine Kontaktdaten. Edgar bestätigt deinen Termin und das Lieferdatum.", "Deixa o teu link e os teus dados. O Edgar confirma a vaga e a data de entrega."),
  url: L("Link de tu tienda", "Your store link", "Link zu deinem Store", "Link da tua loja"),
  phone: L("WhatsApp con código de país", "WhatsApp with country code", "WhatsApp mit Ländervorwahl", "WhatsApp com indicativo do país"),
  done: L("Recibimos tu tienda. Te contactaremos para confirmar el cupo y la fecha. La revisión llega por un link privado en 72 horas desde la confirmación del cupo.", "We received your store. We'll contact you to confirm your slot and date. Your private review link arrives within 72 hours of slot confirmation.", "Wir haben deinen Store erhalten. Wir melden uns zur Terminbestätigung. Dein privater Analyse-Link kommt innerhalb von 72 Stunden nach Bestätigung.", "Recebemos a tua loja. Vamos contactar-te para confirmar a vaga e a data. O link privado chega em 72 horas após a confirmação da vaga."),
  privacy: L("Usamos tus datos para responder a esta solicitud. No necesitamos tu contraseña ni cambiamos tu Shopify. La propuesta es privada.", "We use your details to respond to this request. No password needed and no changes to your Shopify store. Your proposal stays private.", "Wir nutzen deine Daten für diese Anfrage. Kein Passwort nötig; wir ändern deinen Shopify-Store nicht. Der Vorschlag bleibt privat.", "Usamos os teus dados para responder a este pedido. Não precisamos da tua palavra-passe nem alteramos a tua Shopify. A proposta é privada."),
  privacyLink: L("Privacidad", "Privacy", "Datenschutz", "Privacidade"),
  proofTitle: L("Una tienda real. Trabajo nuestro.", "A real store. Our work.", "Ein echter Store. Unsere Arbeit.", "Uma loja real. Trabalho nosso."),
  proof: L("En Eleonora Morales construimos la tienda y conectamos catálogo, clientas y atención. Puedes ver el caso y el trabajo que hay detrás.", "For Eleonora Morales, we built the store and connected the catalog, customers and customer service. Explore the case and the work behind it.", "Für Eleonora Morales haben wir den Store aufgebaut und Katalog, Kundinnen und Betreuung verbunden. Sieh dir den Fall und unsere Arbeit an.", "Para a Eleonora Morales construímos a loja e ligámos catálogo, clientes e atendimento. Vê o caso e o trabalho por trás."),
  caseLink: L("Ver el caso Eleonora Morales", "See the Eleonora Morales case", "Fall Eleonora Morales ansehen", "Ver o caso Eleonora Morales"),
  includes: L("Qué recibes", "What you receive", "Was du bekommst", "O que recebes"),
  steps: [
    L("Revisión de lo que encuentra una persona al entrar a tu tienda desde el celular, con evidencia de las fricciones visibles.", "A review of what visitors encounter on mobile, with evidence of visible friction.", "Eine Prüfung des mobilen Einkaufserlebnisses mit Belegen für sichtbare Hürden.", "Uma análise do que a pessoa encontra no telemóvel, com evidência das fricções visíveis."),
    L("Una propuesta funcional de una ficha de producto junto a la actual, para que puedas comparar.", "A working product page proposal beside your current page, so you can compare.", "Eine funktionierende Produktseiten-Version neben deiner aktuellen Seite zum Vergleichen.", "Uma proposta funcional de uma página de produto ao lado da atual, para comparares."),
    L("Un índice de 0 a 100 con criterios y evidencia. Lo que requiera acceso a tus datos se señala como pendiente.", "A 0–100 score with criteria and evidence. Anything requiring access to your data is marked as pending.", "Eine Bewertung von 0 bis 100 mit Kriterien und Belegen. Alles, was Zugriff auf deine Daten braucht, bleibt ausdrücklich offen.", "Um índice de 0 a 100 com critérios e evidência. O que exigir acesso aos teus dados fica identificado como pendente."),
  ],
  fit: L("Pensado para marcas que ya venden por Shopify y quieren mejorar su conversión. La revisión no obliga a contratar ni garantiza un aumento de ventas.", "For brands already selling on Shopify that want to improve conversion. No obligation to hire us and no guaranteed sales increase.", "Für Marken, die bereits über Shopify verkaufen und ihre Conversion verbessern möchten. Ohne Auftragspflicht oder Garantie für höhere Verkäufe.", "Para marcas que já vendem na Shopify e querem melhorar a conversão. Sem obrigação de contratar ou garantia de aumento de vendas."),
  more: L("Conocer Monza Lab", "Explore Monza Lab", "Monza Lab kennenlernen", "Conhecer a Monza Lab"),
};
